USE JoystickJury;

DROP TABLE IF EXISTS GameReview;

CREATE TABLE GameReview(

GameReviewID INT NOT NULL UNIQUE AUTO_INCREMENT, 
UserID INT NOT NULL,
GameID INT NOT NULL, 
ReviewTitle VARCHAR(64) NOT NULL,
ReviewScore TINYINT NOT NULL,
ReviewText VARCHAR(512) NULL,
ReviewPostDate DATE NOT NULL,

INDEX GameReviewIDIndex(GameReviewID),
INDEX GameIDIndex(GameID),
INDEX UserIDIndex(UserID),
CONSTRAINT ValidGameReviewScore CHECK(ReviewScore > 0 AND ReviewScore <= 5),
CONSTRAINT FKGameReviewToGame FOREIGN KEY(GameID) REFERENCES Game(GameID) ON UPDATE NO ACTION ON DELETE CASCADE,
CONSTRAINT FKGameReviewToUser FOREIGN KEY(UserID) REFERENCES User(UserID) ON UPDATE NO ACTION ON DELETE CASCADE

);