USE JoystickJury;

DROP TABLE IF EXISTS GameGenre;

CREATE TABLE GameGenre(

GameID INT NOT NULL,
GameGenre VARCHAR(16),

INDEX GameIDIndex(GameID),
INDEX GameGenreIndex(GameGenre),
CONSTRAINT FKGameGenreToGame FOREIGN KEY(GameID) REFERENCES Game(GameID) ON UPDATE NO ACTION ON DELETE CASCADE

);